- name: play level variables #task level variables
  hosts: local
  connection: local
  vars:
    iam: "malli "
    role: "DEVSECOPS WITH AWS"
  tasks:
    - name: print variables
      vars: 
        iam: "arunkumar"
      ansible.builtin.debug:
        msg: " my name is {{ iam }}, role is: {{ role }} "
       