- name: install the package
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install the packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx

